CREATE TABLE GSALES(
GSID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
GID  INT NOT NULL,
SID  INT NOT NULL,
SDATE DATETIME,
SNUM INT NOT NULL,
FOREIGN KEY(GID) REFERENCES GOODS(GID),
FOREIGN KEY(SID) REFERENCES SALESMAN(SID)
ON UPDATE CASCADE
);